spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: gsm_demo
    password: Admin123
    driver-class-name: oracle.jdbc.OracleDriver
    platform: org.hibernate.dialect.H2Dialect
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
